---
- name: Get Device Facts
  hosts: all
  connection: local
  gather_facts: no
  roles:
   -  Juniper.junos
  vars:
    crenditial:
      host: "{{ ansible_host }}"
      port: "{{ netconf_port }}"
      username: "{{ ansible_user}}"
      password: "{{ ansible_ssh_pass }}"

  tasks:
#  - name: Display all variables/facts know for a host
#    debug:
#      var: hostvars[inventory_hostname]

  - name: Checking NETCONF connectivity
    wait_for: host={{ ansible_host }} port={{ netconf_port }} timeout=5

  - name: Get JUNOS-style facts
    junos_get_facts:
      host: "{{ ansible_host }}"
      user: automation
      passwd: automation123

#  - name: ABCD
#    wait-for: host={{ ansible_host }} port={{ netconf_port }} timeout=5
